### ISSUE TITLE
[docs]Check and improve the `docs/README_EN.md`

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#292]
## Overview

The README is currently written in Japanese.

In order to connect with more OSS developers,
I see a lot of value in translating the documentation into English.

- #291 

A `docs/README_EN.md` has already been created in this PR.
This needs to be checked and improved.

## Task list

- [ ] check `docs/README_EN.md`

If you find any problem, 

- [ ] please report them in Create new Issue.
- [ ] If workable, it will be assigned by the maintainer immediately!

## Others

**Once you have found a modification, please make an issue!
This avoids multiple contributors making the same correction.**

## Bundle of currently reported issues

- [x] #293 

---

Thank you for your interest in this issue 🚀.

**Comment by PAVAN507-STAR** [comment]
Hii @kazzyfrog.I would like to take up all the issues related to converting the readme.md to english properly if u don't mind

**Comment by kazzyfrog** [comment]
His @PAVAN507-STAR .
I would appreciate it. ;)
